import React, {FC, ReactNode, useEffect} from 'react';
import Head from 'next/head';

import {siteName} from 'dictionaries/site.dictionary';
import DefaultMasterpage from './default/default.';
import EmptyMasterpage from './empty/empty';

interface IMasterPageProps {
  template?: 'default' | 'empty'
  title?: string
  subtitle?: string | string[]
  bodyClassName?: string
  children: ReactNode
}

const MasterPage: FC<IMasterPageProps> = ({template = 'default', title = siteName, subtitle, bodyClassName, children}) => {
  useEffect(() => {
    if (bodyClassName) document.querySelector('body')?.classList.add(bodyClassName);

    return () => {
      if (bodyClassName) document.querySelector('body')?.classList.remove(bodyClassName);
    };
  }, [bodyClassName]);

  return (
    <>
      <Head>
        <title>
          {subtitle && `${Array.isArray(subtitle) ? subtitle.join(' - ') : subtitle} - `}
          {title}
        </title>
        <meta name="description" content="Generated by create next app" key="meta-description" />
        <link rel="icon" href="/favicon.ico" />
        {/* Generate your complete favicon using https://realfavicongenerator.net/ */}
      </Head>
      {
        {
          default: <DefaultMasterpage>{children}</DefaultMasterpage>,
          empty: <EmptyMasterpage>{children}</EmptyMasterpage>
        }[template]
      }
    </>
  );
};

export default MasterPage;
