# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm dependencies
        run: yarn --pure-lockfile --non-interactive

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: node_modules

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v3

      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build

      - name: Test css
        run: yarn test:css

      - name: Test js
        run: yarn test:js

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: next build
        run: yarn build
